# Generated by Django 5.2.7 on 2025-10-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_memebership_customer_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
